/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomRoundedTextField: typeof import('./src/components/custom/CustomRoundedTextField.vue')['default']
    FormLogin: typeof import('./src/components/FormLogin.vue')['default']
    FormSignUp: typeof import('./src/components/FormSignUp.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderLogin: typeof import('./src/components/HeaderLogin.vue')['default']
    ListTransactable: typeof import('./src/components/ListTransactable.vue')['default']
    ListTransaction: typeof import('./src/components/ListTransaction.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    LoginHeader: typeof import('./src/components/LoginHeader.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUpForm: typeof import('./src/components/SignUpForm.vue')['default']
    Transactable: typeof import('./src/components/Transactable.vue')['default']
    TransactableItem: typeof import('./src/components/TransactableItem.vue')['default']
    TransactableList: typeof import('./src/components/TransactableList.vue')['default']
    UnauthenticatedHeader: typeof import('./src/components/UnauthenticatedHeader.vue')['default']
  }
}
