/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BalanceResumeItem: typeof import('./src/components/BalanceResumeItem.vue')['default']
    CustomRoundedTextField: typeof import('./src/components/CustomRoundedTextField.vue')['default']
    FilterByMonthYear: typeof import('./src/components/FilterByMonthYear.vue')['default']
    LeftSideMenu: typeof import('./src/components/LeftSideMenu.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUpForm: typeof import('./src/components/SignUpForm.vue')['default']
    TransactableItem: typeof import('./src/components/TransactableItem.vue')['default']
    TransactableList: typeof import('./src/components/TransactableList.vue')['default']
    TransactionAddButton: typeof import('./src/components/TransactionAddButton.vue')['default']
    TransactionResumeItem: typeof import('./src/components/TransactionResumeItem.vue')['default']
    TransactionRoundedAddButton: typeof import('./src/components/TransactionRoundedAddButton.vue')['default']
    UnauthenticatedHeader: typeof import('./src/components/UnauthenticatedHeader.vue')['default']
  }
}
