/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BalanceResumeItem: typeof import('./src/components/BalanceResumeItem.vue')['default']
    CardResumeTransaction: typeof import('./src/components/CardResumeTransaction.vue')['default']
    CustomRoundedTextField: typeof import('./src/components/CustomRoundedTextField.vue')['default']
    FilterByMonthYear: typeof import('./src/components/FilterByMonthYear.vue')['default']
    FormLogin: typeof import('./src/components/FormLogin.vue')['default']
    FormSignUp: typeof import('./src/components/FormSignUp.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderLogin: typeof import('./src/components/HeaderLogin.vue')['default']
    LeftSideMenu: typeof import('./src/components/LeftSideMenu.vue')['default']
    ListTransactable: typeof import('./src/components/ListTransactable.vue')['default']
    ListTransaction: typeof import('./src/components/ListTransaction.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    LoginHeader: typeof import('./src/components/LoginHeader.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUpForm: typeof import('./src/components/SignUpForm.vue')['default']
    Transactable: typeof import('./src/components/Transactable.vue')['default']
    TransactableItem: typeof import('./src/components/TransactableItem.vue')['default']
    TransactableList: typeof import('./src/components/TransactableList.vue')['default']
    TransactionAddButton: typeof import('./src/components/TransactionAddButton.vue')['default']
    TransactionResumeItem: typeof import('./src/components/TransactionResumeItem.vue')['default']
    TransactionRoudedAddButton: typeof import('./src/components/TransactionRoudedAddButton.vue')['default']
    TransactionRoundedAddButton: typeof import('./src/components/TransactionRoundedAddButton.vue')['default']
    TransctionAddButton: typeof import('./src/components/TransctionAddButton.vue')['default']
    UnauthenticatedHeader: typeof import('./src/components/UnauthenticatedHeader.vue')['default']
  }
}
